spring.application.name=backend

# --- Configuración del Servidor ---
server.port=8080

# --- Configuración de MySQL ---
# Cambia 'feriaplus_db' por el nombre que le hayas dado a tu esquema en MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/feriaplus_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate ---
# 'update' creará automáticamente las tablas (Usuarios, Eventos, etc.) al arrancar
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
